import { useEffect, useState } from "react";
import { fetchAlerts } from "../services/alertService";
import "../styles/alerts.css";

function Alerts() {
  const [alerts, setAlerts] = useState([]);

  useEffect(() => {
    const loadAlerts = () => {
      fetchAlerts().then(setAlerts);
    };

    loadAlerts();                 // initial fetch
    const interval = setInterval(loadAlerts, 2000); // 🔥 auto-refresh

    return () => clearInterval(interval);
  }, []);

  return (
    <div className="page">
      <h1>Alerts</h1>
      <p className="subtitle">
        Live alerts generated by the detection engine
      </p>

      <div className="alerts-list">
        {alerts.length === 0 && (
          <p className="subtitle">No alerts recorded yet</p>
        )}

        {alerts.map((alert, index) => (
          <div
            key={index}
            className={`alert-card ${alert.severity.toLowerCase()}`}
          >
            <div className="alert-header">
              <span className="alert-severity">{alert.severity}</span>
              <span className="alert-time">{alert.time}</span>
            </div>

            <div className="alert-message">{alert.message}</div>

            <div className="alert-footer">
              Camera: <strong>{alert.camera}</strong>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Alerts;
